config/routes.rb
Rails.application.routes.draw do
 root "admin/posts#index"
 devise_for :users
   namespace :admin do 
   	resources :posts
   	resources :categories
   	get 'posts/:id/count', to: 'posts#view_count', as: 'view_count'

   end
  get 'search', to: 'admin/posts#search'

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/category.rb
class Category < ApplicationRecord
	has_many :post_categories
	has_many :posts, through: :post_categories
end

app/models/post.rb
class Post < ApplicationRecord
	has_one_attached :image
	has_many :post_categories
	has_many :categories, through: :post_categories
	has_one :post_view
end

app/models/post_category.rb
class PostCategory < ApplicationRecord
	belongs_to :post
	belongs_to :category
end

app/models/post_view.rb
class PostView < ApplicationRecord
	belongs_to :post
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/admin/categories_controller.rb
# frozen_string_literal: true
class Admin::CategoriesController < ApplicationController
	before_action :find_category, only: %i[show  edit update destroy]
	def index
		@categories = Category.all
	end

	def show
		
	end

	def new
		@category = Category.new
	end

	def create
		@category = Category.new(category_params)
		if @category.save 
			redirect_to admin_category_path(@category)
		else
			render 'new'
		end	
	end

	private

	def find_category
		@category = Category.find(params[:id])
	end

	def category_params
		params.require(:category).permit(:title)
	end
end

app/controllers/admin/posts_controller.rb
# frozen_string_literal: true

class Admin::PostsController < ApplicationController
	before_action :find_post, only: %i[show  edit update destroy view_count]
	def index
		@posts = Post.all.page(params[:page])
	end

 	def new
 		@post = Post.new
 		@categories = Category.all
 		
 	end

 	def create
 		@post = Post.new(post_params)
 		if @post.save
 			flash[:success] = t('admin.posts.create.success')
 			redirect_to admin_post_path(@post)
 		else
 			flash[:danger] = t('admin.posts.errors')
 			render 'new'
 		end		
 	end

 	def edit
 		@categories = Category.all
 	end

 	def update

 		if @post.update(post_params)
 			flash[:success] = t('admin.posts.update')
 			redirect_to admin_post_path(@post)
 		else
 			render 'edit'
 		end	
 	end

 	def destroy
 		@post.destroy
 		redirect_to admin_posts_path
 	end

 	def view_count
 		if @post.post_view.present?
 			@count = @post.post_view
 			@view = @count.view_count + 1
 			@count.update_attributes(view_count: @view )
 			redirect_to admin_post_path(@post)
 		else
 			@post_view = @post.create_post_view(view_count: 1)

 			if @post_view.save
 				redirect_to admin_post_path(@post)
 			end	
 		end	

 	end

 	def search
 		if params[:q].present?
 			@posts = Post.where('title LIKE ?','%' + params[:q] +'%')
 		end	
 		# if params[:q].length < 3
 		# redirect_to admin_posts_path
 		# end	
 		if params[:q] == ''
 			redirect_to admin_posts_path
 		end
 	end

 	private
 		def find_post
 			@post = Post.find(params[:id])
 		end

 		def post_params
 			params.require(:post).permit(:title, :body, :image, :category_ids)
 		end
end

app/controllers/anun_controller.rb
class AnunController < ApplicationController
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
end

app/helpers/admin/categories_helper.rb
module Admin::CategoriesHelper
end

app/helpers/admin/posts_helper.rb
module Admin::PostsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/admin/categories/index.html.erb
<div class="row bg-light" style="height: 600px">
	<div class="container">
		<h1 class="text-centr primary">All Caterory</h1>
		<% @categories.each do |category| %>
			<p><%= category.title %></p>
		<% end %>
	</div>
</div>

app/views/admin/categories/new.html.erb
<div class="row bg-secondary" style="height: 600px">
	<div class="container ">
		<h1 class="text-center text-warning">Create New Catergory</h1>
		<%= form_for :category, url: admin_categories_path do |f| %>
			<div class="form-group">
				<%= f.label :title %>
				<%= f.text_field :title , class: "form-control" %>
			</div>
			<div class="form-group">
				<%= f.submit  class: "btn btn-warning" %>
			</div>
		<% end %>
	</div>
</div>

app/views/admin/categories/show.html.erb
<div class="container-fluid bg-secondary">
	<div class="row">
		<div class="col-md-3"></div>
		<div class="col-md-6"> 
			<h1 class="text-center text-warning"><%= @category.title %></h1>
		</div>
		<div class="col-md-3"></div>
	</div>
</div>

app/views/admin/posts/edit.html.erb
<div class="row  new" style="height: 600px">
	<div class="container ">
		<h1 class="text-center text-secondary">Edit Post</h1>
		<%= form_for [:admin, @post] do |f| %>
			<div class="form-group">
				<%= f.label :title, class: "text-secondary" %>
				<%= f.text_field :title , class: "form-control" %>
			</div>
			<div class="form-group">
				<%= f.label :body,  class: "text-secondary" %>
				<%= f.text_area :body , class: "form-control" %>
			</div>
			<div class="form-group">
				<%= f.label :image,class: "text-secondary" %>
				<%= f.file_field :image, class: "form-control" %>
			</div>
			<div class="form-group">
				<%= f.label :category, class: "text-secondary" %>
				<%= f.collection_select :category_ids, @categories, :id, :title, include_blank: 'Choose Category', class: "form-group" %>
			</div>
			<div class="form-group">
				<%= f.submit  class: "btn btn-secondary" %>
			</div>
		<% end %>
	</div>
</div>

app/views/admin/posts/index.html.erb
<div class="container">
	<h1 class="text-center text-secondary">All Posts</h1>
	<% @posts.each do |post| %>
		<p><%= link_to post.title, admin_view_count_path(post) %></p>
	<% end %>
	<%= paginate @posts %>

</div>

app/views/admin/posts/new.html.erb
<div class="row  new" style="height: 600px">
	<div class="container ">
		<h1 class="text-center text-secondary">Create New post</h1>
		<%= form_for :post, url: admin_posts_path do |f| %>
			<div class="form-group">
				<%= f.label :title, class: "text-secondary" %>
				<%= f.text_field :title , class: "form-control" %>
			</div>
			<div class="form-group">
				<%= f.label :body,  class: "text-secondary" %>
				<%= f.text_area :body , class: "form-control" %>
			</div>
			<div class="form-group">
				<%= f.label :image,class: "text-secondary" %>
				<%= f.file_field :image, class: "form-control" %>
			</div>
			<div class="form-group">
				<%= f.label :category, class: "text-secondary" %>
				<%= f.collection_select :category_ids, @categories, :id, :title, include_blank: 'Choose Category', class: "form-group" %>
			</div>
			<div class="form-group">
				<%= f.submit  class: "btn btn-secondary" %>
			</div>
		<% end %>
	</div>
</div>

app/views/admin/posts/search.html.erb
<h1>Search Results</h1>
<% if @posts.present? %>
	<% @posts.each do |post| %>
		<%= post.title %>
	<% end %>		
<% end %>	

app/views/admin/posts/show.html.erb
<%= @post.title %>
<p><%= @post.body %></p>
<% if @post.post_view.present? %>
	<p><%= @post.post_view.view_count %></p>
<% end %>	
<% @post.categories.each do |category| %>
	<%= category.title %>
<% end %>
<%= link_to "delate", [:admin, @post], method: :delete, data: { confirm: 'Are you sure?' }, class: "btn btn-danger" %>
<p>hello world</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Pordz</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>

    <%= render 'shared/header' %>
    <%= render 'shared/flash' %>
    <%= yield %>
  </body>
</html>

app/views/shared/_flash.html.erb
<% if flash.keys.count > 0 %>
	<% flash.each do |name,msg| %>
		<div class="alert alert-<%= name %> ">
			<%= msg %>
		</div>
	<% end %>
<% end %>	

app/views/shared/_header.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <a class="navbar-brand" href="#">News</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item active">
        <a class="nav-link" href="#">Politics <span class="sr-only">(current)</span></a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="#">Economy</a>
      </li>
     <li class="nav-item dropdown">
        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
          Dropdown
        </a>
        <div class="dropdown-menu" aria-labelledby="navbarDropdown">
          <a class="dropdown-item" href="#">Action</a>
          <a class="dropdown-item" href="#">Another action</a>
          <div class="dropdown-divider"></div>
          <a class="dropdown-item" href="#">Something else here</a>
        </div>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="#">Contact Us</a>
      </li>
    </ul>
    <% if current_user %>
      <%= link_to "Logout", destroy_user_session_path, data: { method: 'delete' }, class: "btn btn-outline-success" %>
    <% else %>
      <%= link_to "Login", new_user_session_path, class: "btn btn-outline-success" %>
      <%= link_to "Sign up", new_user_registration_path, class: "btn btn-outline-success" %> 
    <% end %>
    <form class="form-inline my-2 my-lg-0" action="search">
      <input class="form-control mr-sm-2" type="search" placeholder="Search" aria-label="Search" name="q">
      <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
    </form>
  </div>
</nav>